from dataclasses import dataclass, field
from typing import List, Dict, Set
import numpy as np
from enum import Enum


class MechanismType(Enum):
    """Enum for different types of mechanisms."""

    THREE_BAR = "3bar"
    FOUR_BAR = "4bar"
    CAM = "cam"
    PARAMETRIC = "parametric"


@dataclass
class MechanismParameter:
    """Represents a single parameter of a mechanism."""

    name: str
    value: float
    min_val: float
    max_val: float
    step: float


@dataclass
class MotionCurve:
    """Represents the motion curve generated by a mechanism."""

    points: np.ndarray = field(
        default_factory=lambda: np.empty((0, 2))
    )  # Nx2 array of 2D points
    period: float = 0.0
    attachment_point: np.ndarray = field(
        default_factory=lambda: np.zeros(2)
    )  # 2D point
    parameter_vector: np.ndarray = field(
        default_factory=lambda: np.array([])
    )  # Parameters that generated this curve


@dataclass
class MechanismTemplate:
    """Template for a mechanism, defining its type and parameters."""

    type: MechanismType
    parameters: List[MechanismParameter] = field(default_factory=list)
    enabled: bool = True


@dataclass
class PrecomputedMotionEntry:
    """An entry in the precomputed motion database."""

    mechanism_type: MechanismType
    parameters: np.ndarray
    motion_curve: MotionCurve
    features: np.ndarray  # Feature vector for similarity matching


@dataclass
class MechanismCandidate:
    """A candidate mechanism recommended for a target motion."""

    mechanism_type: MechanismType
    parameters: Dict[str, float] = field(default_factory=dict)
    motion_curve: MotionCurve = field(default_factory=MotionCurve)
    similarity_score: float = 0.0
    transform_matrix: np.ndarray = field(
        default_factory=lambda: np.eye(3)
    )  # Alignment transformation
