"""
MechanismDesignTab Adapter.

Bridges MechanismDesignTab to ProjectStateManager.

Data Flow:
- Tab → StateManager: mechanism_parameters_changed, mechanism_path_generated
- StateManager → Tab: parts_changed, skeleton_changed, paths_changed, mechanisms_changed

Architecture: Application Layer (Hexagonal)
Pattern: Adapter
"""
from __future__ import annotations

import logging
import uuid
from pathlib import Path
from typing import TYPE_CHECKING, Any

from PyQt6.QtGui import QPainterPath

from ..models import (
    MechanismData,
    PartData,
    PathData,
    SkeletonData,
)
from .base import TabAdapter

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)


class MechanismDesignTabAdapter(TabAdapter):
    """
    Adapter for MechanismDesignTab.

    Transforms:
    - mechanism_parameters_changed (str, dict) → update_mechanism
    - mechanism_path_generated (str, QPainterPath) → set_path (for mechanism output)

    Subscribes to:
    - parts_changed → set_parts_data
    - skeleton_changed → on_skeleton_updated, cache_initial_skeleton
    - paths_changed → set_path_data_from_editor
    - mechanisms_changed → (reload mechanism layers)
    """

    def _connect_tab_signals(self) -> None:
        """Connect to MechanismDesignTab's output signals."""
        if not self._tab:
            return

        self._tab.mechanism_parameters_changed.connect(self._on_mechanism_params_changed)
        self._tab.mechanism_path_generated.connect(self._on_mechanism_path_generated)
        logger.debug("MechanismDesignTabAdapter: Connected to tab signals")

    def _subscribe_to_state(self) -> None:
        """Subscribe to state manager signals."""
        self._state_manager.parts_changed.connect(self._on_state_parts_changed)
        self._state_manager.skeleton_changed.connect(self._on_state_skeleton_changed)
        self._state_manager.paths_changed.connect(self._on_state_paths_changed)
        self._state_manager.mechanisms_changed.connect(self._on_state_mechanisms_changed)
        logger.debug("MechanismDesignTabAdapter: Subscribed to state changes")

    def _disconnect_tab_signals(self) -> None:
        """Disconnect from tab signals."""
        if not self._tab:
            return

        try:
            self._tab.mechanism_parameters_changed.disconnect(self._on_mechanism_params_changed)
            self._tab.mechanism_path_generated.disconnect(self._on_mechanism_path_generated)
        except TypeError:
            pass

    def _unsubscribe_from_state(self) -> None:
        """Unsubscribe from state manager."""
        try:
            self._state_manager.parts_changed.disconnect(self._on_state_parts_changed)
            self._state_manager.skeleton_changed.disconnect(self._on_state_skeleton_changed)
            self._state_manager.paths_changed.disconnect(self._on_state_paths_changed)
            self._state_manager.mechanisms_changed.disconnect(self._on_state_mechanisms_changed)
        except TypeError:
            pass

    # =========================================================================
    # TAB → STATE MANAGER
    # =========================================================================

    def _on_mechanism_params_changed(self, mechanism_id: str, params: dict) -> None:
        """
        Handle mechanism_parameters_changed signal from MechanismDesignTab.

        Args:
            mechanism_id: The mechanism layer ID
            params: Updated mechanism parameters
        """
        logger.info(f"MechanismDesignTabAdapter: Mechanism params changed for '{mechanism_id}'")

        try:
            # Get existing mechanism or create new one
            existing = self._state_manager.state.get_mechanism(mechanism_id)

            if existing:
                # Update existing mechanism
                updated = existing.with_params(params)
                self._state_manager.update_mechanism(updated)
            else:
                # Create new mechanism (need part_name and type from params)
                part_name = params.get("part_name", "")
                mech_type = params.get("type", "4_bar_linkage")

                if part_name:
                    mechanism = MechanismData(
                        id=mechanism_id,
                        part_name=part_name,
                        type=mech_type,
                        params=params,
                        enabled=True,
                    )
                    self._state_manager.add_mechanism(mechanism)

        except Exception as e:
            logger.exception(f"Error processing mechanism_params_changed: {e}")

    def _on_mechanism_path_generated(self, part_name: str, qpath: QPainterPath) -> None:
        """
        Handle mechanism_path_generated signal from MechanismDesignTab.

        This is the output path generated by a mechanism for a part.

        Args:
            part_name: Name of the part
            qpath: The generated QPainterPath
        """
        logger.debug(f"MechanismDesignTabAdapter: Mechanism path generated for '{part_name}'")

        # Note: This path is the OUTPUT of mechanism computation,
        # not the INPUT path from EditorTab. We might want to store
        # this differently or ignore it depending on requirements.

    # =========================================================================
    # STATE MANAGER → TAB
    # =========================================================================

    def _on_state_parts_changed(self, parts: dict[str, PartData]) -> None:
        """
        Handle parts changes from state manager.

        Transforms PartData to PartInfo and calls tab's set_parts_data.
        """
        if not self._tab:
            return

        logger.info(f"MechanismDesignTabAdapter: Forwarding {len(parts)} parts to tab")

        try:
            # Transform PartData to PartInfo format
            parts_info = self._transform_parts_to_partinfo(parts)

            # Call tab's method
            if hasattr(self._tab, "set_parts_data"):
                self._tab.set_parts_data(parts_info)

        except Exception as e:
            logger.exception(f"Error forwarding parts to tab: {e}")

    def _on_state_skeleton_changed(self, skeleton: SkeletonData | None) -> None:
        """
        Handle skeleton changes from state manager.

        Forwards to tab's on_skeleton_updated and cache_initial_skeleton.
        """
        if not self._tab:
            return

        # Convert to dict format
        skeleton_dict = skeleton.to_dict() if skeleton else None

        # Update display
        if hasattr(self._tab, "on_skeleton_updated"):
            self._tab.on_skeleton_updated(skeleton_dict)

        # Cache initial skeleton
        if hasattr(self._tab, "cache_initial_skeleton"):
            self._tab.cache_initial_skeleton(skeleton_dict)

    def _on_state_paths_changed(self, paths: dict[str, PathData]) -> None:
        """
        Handle path changes from state manager.

        Converts PathData to QPainterPath and forwards to tab.
        """
        if not self._tab:
            return

        logger.info(f"MechanismDesignTabAdapter: Forwarding {len(paths)} paths to tab")

        try:
            # Convert PathData to QPainterPath dict
            qpath_dict: dict[str, QPainterPath] = {}
            for part_name, path_data in paths.items():
                if path_data.enabled:
                    qpath_dict[part_name] = self._transform_pathdata_to_qpath(path_data)

            # Call tab's method
            if hasattr(self._tab, "set_path_data_from_editor"):
                self._tab.set_path_data_from_editor(qpath_dict)

        except Exception as e:
            logger.exception(f"Error forwarding paths to tab: {e}")

    def _on_state_mechanisms_changed(self, mechanisms: dict[str, MechanismData]) -> None:
        """
        Handle mechanism changes from state manager.

        This is for cases where mechanisms are modified externally
        (e.g., loaded from project file, undo/redo).

        Syncs the tab's mechanism_layers with the state by:
        1. Removing mechanisms no longer in state
        2. Adding new mechanisms from state
        3. Updating existing mechanisms with changed params
        """
        if not self._tab:
            return

        logger.info(f"MechanismDesignTabAdapter: Syncing {len(mechanisms)} mechanisms from state")

        try:
            # Get current mechanism IDs from tab
            current_ids = set(self._tab.mechanism_layers.keys()) if hasattr(self._tab, 'mechanism_layers') else set()
            state_ids = set(mechanisms.keys())
            changed_or_added_ids: list[str] = []
            ui_list_needs_refresh = False

            # Remove mechanisms that are no longer in state
            ids_to_remove = current_ids - state_ids
            for mech_id in ids_to_remove:
                logger.debug(f"Removing mechanism '{mech_id}' (not in state)")
                if hasattr(self._tab, '_mvp_presenter') and hasattr(self._tab._mvp_presenter, 'remove_mechanism_layer'):
                    self._tab._mvp_presenter.remove_mechanism_layer(mech_id)
                elif hasattr(self._tab, 'mechanism_layers'):
                    # Fallback: direct removal
                    self._tab.mechanism_layers.pop(mech_id, None)
                    if hasattr(self._tab, 'mechanism_enabled_state'):
                        self._tab.mechanism_enabled_state.pop(mech_id, None)
                ui_list_needs_refresh = True

            # Add or update mechanisms from state
            for mech_id, mech_data in mechanisms.items():
                if mech_id in current_ids:
                    # Update existing mechanism
                    if hasattr(self._tab, 'mechanism_layers'):
                        existing = self._tab.mechanism_layers.get(mech_id, {})
                        if self._layer_matches_mechanism_data(existing, mech_data):
                            if hasattr(self._tab, "mechanism_enabled_state"):
                                self._tab.mechanism_enabled_state[mech_id] = mech_data.enabled
                            continue

                        layer_data = self._transform_mechanism_to_layer_data(mech_data)
                        # Preserve visual_items from existing layer_data
                        layer_data["visual_items"] = existing.get("visual_items", [])
                        self._tab.mechanism_layers[mech_id] = layer_data
                        if hasattr(self._tab, "mechanism_enabled_state"):
                            self._tab.mechanism_enabled_state[mech_id] = mech_data.enabled
                        logger.debug(f"Updated mechanism '{mech_id}'")
                        changed_or_added_ids.append(mech_id)
                else:
                    # Add new mechanism
                    logger.debug(f"Adding mechanism '{mech_id}' from state")
                    layer_data = self._transform_mechanism_to_layer_data(mech_data)
                    if hasattr(self._tab, '_mvp_presenter') and hasattr(self._tab._mvp_presenter, 'add_mechanism_layer'):
                        self._tab._mvp_presenter.add_mechanism_layer(mech_id, layer_data)
                    elif hasattr(self._tab, 'mechanism_layers'):
                        self._tab.mechanism_layers[mech_id] = layer_data
                        if hasattr(self._tab, 'mechanism_enabled_state'):
                            self._tab.mechanism_enabled_state[mech_id] = mech_data.enabled
                    changed_or_added_ids.append(mech_id)
                    ui_list_needs_refresh = True

            # Update the UI list only when membership changed
            if ui_list_needs_refresh and hasattr(self._tab, '_update_mechanism_layers_list'):
                self._tab._update_mechanism_layers_list()

            # Regenerate visuals only for mechanisms that actually changed
            for mech_id in changed_or_added_ids:
                mech_data = mechanisms.get(mech_id)
                if mech_data is None:
                    continue
                layer_data = self._tab.mechanism_layers.get(mech_id) if hasattr(self._tab, 'mechanism_layers') else None
                if layer_data and hasattr(self._tab, '_generate_mechanism_visuals_directly'):
                    self._tab._generate_mechanism_visuals_directly(
                        mech_id,
                        mech_data.type,
                        dict(mech_data.params) if mech_data.params else {},
                        layer_data
                    )

        except Exception as e:
            logger.exception(f"Error syncing mechanisms from state: {e}")

    def _layer_matches_mechanism_data(
        self,
        existing_layer: Any,
        mech_data: MechanismData,
    ) -> bool:
        """Fast comparison to skip unnecessary mechanism re-renders."""
        if not isinstance(existing_layer, dict):
            return False

        if str(existing_layer.get("part_name", "")) != mech_data.part_name:
            return False
        if str(existing_layer.get("type", "")) != mech_data.type:
            return False

        existing_params = existing_layer.get("params", {})
        if not isinstance(existing_params, dict):
            return False
        if existing_params != (dict(mech_data.params) if mech_data.params else {}):
            return False

        existing_enabled = bool(existing_layer.get("enabled", True))
        if existing_enabled != mech_data.enabled:
            return False

        payload = dict(mech_data.layer_data) if mech_data.layer_data else {}
        if not payload:
            return True

        for key, value in payload.items():
            if key == "generated_path_data":
                cached_generated = existing_layer.get("_generated_path_data")
                if isinstance(cached_generated, dict):
                    existing_generated = cached_generated
                else:
                    existing_generated = self._serialize_qpath_to_payload(
                        existing_layer.get("generated_path")
                    )
                if existing_generated != value:
                    return False
            elif existing_layer.get(key) != value:
                return False
        return True

    # =========================================================================
    # DATA TRANSFORMATIONS
    # =========================================================================

    def _transform_mechanism_to_layer_data(self, mech_data: MechanismData) -> dict[str, Any]:
        """
        Transform MechanismData to layer_data dict format used by MechanismDesignTab.

        Args:
            mech_data: MechanismData from state manager

        Returns:
            Dict in layer_data format for the tab
        """
        layer_data = dict(mech_data.layer_data) if mech_data.layer_data else {}

        generated_path_data = layer_data.pop("generated_path_data", None)
        generated_path = self._transform_serialized_path_to_qpath(generated_path_data)
        if generated_path is not None and not generated_path.isEmpty():
            layer_data["generated_path"] = generated_path
        if isinstance(generated_path_data, dict):
            layer_data["_generated_path_data"] = generated_path_data

        layer_data.update(
            {
                "id": mech_data.id,
                "part_name": mech_data.part_name,
                "type": mech_data.type,
                "params": dict(mech_data.params) if mech_data.params else {},
                "enabled": mech_data.enabled,
            }
        )
        layer_data.setdefault("visual_items", [])  # Populated by visual generation
        return layer_data

    def _transform_serialized_path_to_qpath(self, payload: Any) -> QPainterPath | None:
        """Restore serialized generated-path payload to QPainterPath."""
        if not isinstance(payload, dict):
            return None

        raw_points = payload.get("points")
        if not isinstance(raw_points, list) or not raw_points:
            return None

        qpath = QPainterPath()
        try:
            first = raw_points[0]
            if not isinstance(first, list | tuple) or len(first) < 2:
                return None
            qpath.moveTo(float(first[0]), float(first[1]))

            for point in raw_points[1:]:
                if not isinstance(point, list | tuple) or len(point) < 2:
                    continue
                qpath.lineTo(float(point[0]), float(point[1]))

            if bool(payload.get("is_closed", False)) and len(raw_points) > 2:
                qpath.closeSubpath()
        except Exception:
            logger.debug("Failed to restore generated_path payload", exc_info=True)
            return None

        return qpath

    def _serialize_qpath_to_payload(self, qpath: Any) -> dict[str, Any] | None:
        """Serialize QPainterPath to payload for delta comparison."""
        if not isinstance(qpath, QPainterPath) or qpath.isEmpty():
            return None

        points: list[list[float]] = []
        try:
            for idx in range(qpath.elementCount()):
                elem = qpath.elementAt(idx)
                points.append([float(elem.x), float(elem.y)])
        except Exception:
            return None

        if not points:
            return None

        first = points[0]
        last = points[-1]
        is_closed = abs(first[0] - last[0]) < 1.0 and abs(first[1] - last[1]) < 1.0
        return {"points": points, "is_closed": is_closed}

    def _transform_parts_to_partinfo(
        self,
        parts: dict[str, PartData],
    ) -> dict[str, Any]:
        """
        Transform PartData dict to PartInfo dict format.

        Args:
            parts: Dict of PartData from state manager

        Returns:
            Dict in PartInfo format
        """
        from automataii.domain.project.models import PartInfoModel
        from automataii.presentation.qt.models import PartInfo

        parts_info: dict[str, PartInfo] = {}
        project_dir = self._state_manager.state.project_dir or Path.cwd()

        for name, part_data in parts.items():
            try:
                roi = (
                    list(part_data.roi)
                    if part_data.roi is not None
                    else [part_data.transform.x, part_data.transform.y, 0.0, 0.0]
                )

                model = PartInfoModel(
                    name=name,
                    roi=roi,
                    z_value=float(part_data.z_index),
                    image_path=part_data.texture_path,
                    fill_color=part_data.fill_color,
                    fixed=part_data.fixed,
                    opacity=part_data.opacity,
                    group=part_data.group,
                    original_svg_path=part_data.original_svg_path,
                    enhanced_svg_path=part_data.enhanced_svg_path,
                    effective_bbox_offset_x=part_data.effective_bbox_offset_x,
                    effective_bbox_offset_y=part_data.effective_bbox_offset_y,
                    show_anchor=part_data.show_anchor,
                    local_pivot_offset=(
                        list(part_data.local_pivot_offset)
                        if part_data.local_pivot_offset is not None
                        else None
                    ),
                    anchor_joint_id=part_data.anchor_joint,
                )
                part_info = PartInfo.from_pydantic(model, project_dir=project_dir)
                parts_info[name] = part_info

            except Exception as e:
                logger.warning(f"Error transforming part '{name}': {e}")
                continue

        return parts_info

    def _transform_pathdata_to_qpath(self, path_data: PathData) -> QPainterPath:
        """
        Transform PathData to QPainterPath.

        Args:
            path_data: PathData from state manager

        Returns:
            QPainterPath
        """
        qpath = QPainterPath()

        if not path_data.points:
            return qpath

        points = list(path_data.points)

        # Move to first point
        qpath.moveTo(points[0].x, points[0].y)

        # Line to subsequent points
        for point in points[1:]:
            qpath.lineTo(point.x, point.y)

        # Close path if needed
        if path_data.is_closed and len(points) > 2:
            qpath.closeSubpath()

        return qpath

    # =========================================================================
    # CONVENIENCE METHODS
    # =========================================================================

    def add_mechanism_for_part(
        self,
        part_name: str,
        mechanism_type: str,
        params: dict[str, Any],
    ) -> str:
        """
        Add a new mechanism for a part.

        Args:
            part_name: Name of the part
            mechanism_type: Type of mechanism (e.g., "4_bar_linkage", "cam")
            params: Mechanism parameters

        Returns:
            Generated mechanism ID
        """
        mechanism_id = f"{part_name}_{mechanism_type}_{uuid.uuid4().hex[:8]}"

        mechanism = MechanismData(
            id=mechanism_id,
            part_name=part_name,
            type=mechanism_type,
            params=params,
            enabled=True,
        )

        self._state_manager.add_mechanism(mechanism)
        return mechanism_id

    def remove_mechanism(self, mechanism_id: str) -> None:
        """Remove a mechanism by ID."""
        self._state_manager.remove_mechanism(mechanism_id)
