#!/usr/bin/env python3
"""Generate MotionSmith Sparkle appcasts.

Production OTA feeds are generated by wrapping Sparkle's official
``generate_appcast`` tool. The legacy Python XML generators are retained only
as explicit diagnostic modes and must not be used for production publication.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from urllib.error import URLError
from urllib.request import Request, urlopen

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from automataii.utils.update_config import (  # noqa: E402
    DEFAULT_APPCAST_URL,
    UPDATE_SITE_BASE_URL,
    normalize_release_version,
    validate_signed_appcast,
)

SPARKLE_GENERATE_APPCAST_ENV = "SPARKLE_GENERATE_APPCAST"
SPARKLE_BIN_DIR_ENV = "SPARKLE_BIN_DIR"
SPARKLE_DISTRIBUTION_DIR_ENV = "SPARKLE_DISTRIBUTION_DIR"


class AppcastGenerationError(RuntimeError):
    """Raised when production appcast generation cannot proceed safely."""


def get_file_info(file_path: Path) -> tuple[int, str]:
    """Get file size and SHA-256 hash."""
    import hashlib

    stat = file_path.stat()
    sha256_hash = hashlib.sha256()
    with file_path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            sha256_hash.update(chunk)
    return stat.st_size, sha256_hash.hexdigest()


def resolve_generate_appcast(
    explicit_path: str | None = None,
    *,
    sparkle_bin_dir: str | None = None,
    sparkle_distribution_dir: str | None = None,
    allow_path_lookup: bool = False,
    env: dict[str, str] | None = None,
) -> Path:
    """Resolve the official Sparkle generate_appcast executable."""
    env = env or os.environ.copy()
    candidates: list[Path] = []
    for value in (
        explicit_path,
        env.get(SPARKLE_GENERATE_APPCAST_ENV),
    ):
        if value:
            candidates.append(Path(value))

    for value in (sparkle_bin_dir, env.get(SPARKLE_BIN_DIR_ENV)):
        if value:
            candidates.append(Path(value) / "generate_appcast")

    for value in (sparkle_distribution_dir, env.get(SPARKLE_DISTRIBUTION_DIR_ENV)):
        if value:
            candidates.append(Path(value) / "bin" / "generate_appcast")

    if allow_path_lookup:
        path_value = shutil.which("generate_appcast")
        if path_value:
            candidates.append(Path(path_value))

    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate.resolve()

    raise AppcastGenerationError(
        "Could not find Sparkle generate_appcast. Provide --sparkle-generate-appcast, "
        f"{SPARKLE_GENERATE_APPCAST_ENV}, {SPARKLE_BIN_DIR_ENV}, or "
        f"{SPARKLE_DISTRIBUTION_DIR_ENV}."
    )


def generate_production_appcast(args: argparse.Namespace) -> Path:
    """Generate a signed production appcast using Sparkle's official tool."""
    if not args.artifact:
        raise AppcastGenerationError("At least one --artifact DMG/zip/tar archive is required.")
    if not args.download_url_prefix.startswith("https://"):
        raise AppcastGenerationError("--download-url-prefix must use HTTPS.")

    tool = resolve_generate_appcast(
        args.sparkle_generate_appcast,
        sparkle_bin_dir=args.sparkle_bin_dir,
        sparkle_distribution_dir=args.sparkle_distribution_dir,
        allow_path_lookup=args.allow_path_tool,
    )
    output_dir = args.output_dir
    if args.clean and output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    staged_artifacts: list[Path] = []
    for artifact in args.artifact:
        if not artifact.exists():
            raise AppcastGenerationError(f"Artifact does not exist: {artifact}")
        destination = output_dir / artifact.name
        if artifact.resolve() != destination.resolve():
            shutil.copy2(artifact, destination)
        staged_artifacts.append(destination)

    if args.release_notes:
        if len(staged_artifacts) != 1:
            raise AppcastGenerationError("--release-notes requires exactly one --artifact.")
        if not args.release_notes.exists():
            raise AppcastGenerationError(f"Release notes file does not exist: {args.release_notes}")
        notes_destination = staged_artifacts[0].with_suffix(args.release_notes.suffix)
        shutil.copy2(args.release_notes, notes_destination)

    appcast_name = args.appcast_name
    command = [
        str(tool),
        "--download-url-prefix",
        args.download_url_prefix.rstrip("/") + "/",
        "--link",
        args.link,
        "--maximum-versions",
        str(args.maximum_versions),
        "-o",
        appcast_name,
    ]
    if args.embed_release_notes:
        command.append("--embed-release-notes")
    if args.keychain_account:
        command.extend(["--account", args.keychain_account])

    private_key_input: str | None = None
    if args.private_key_env:
        private_key_input = os.environ.get(args.private_key_env, "")
        if not private_key_input.strip():
            raise AppcastGenerationError(
                f"{args.private_key_env} is required when --private-key-env is used."
            )
        command.extend(["--ed-key-file", "-"])

    command.append(str(output_dir))
    result = subprocess.run(
        command,
        input=private_key_input,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        raise AppcastGenerationError("Sparkle generate_appcast failed.")

    appcast_path = output_dir / appcast_name
    if not appcast_path.exists():
        raise AppcastGenerationError(f"Sparkle did not create expected appcast: {appcast_path}")

    if args.validate:
        expected_artifact = args.expected_artifact or staged_artifacts[0].name
        validation = validate_signed_appcast(
            appcast_path,
            expected_artifact_name=expected_artifact,
            expected_version=args.expected_version,
            expected_url_prefix=args.download_url_prefix,
            payload_dir=output_dir,
        )
        if not validation.passed:
            for error in validation.errors:
                print(f"::error::{error}", file=sys.stderr)
            raise AppcastGenerationError("Generated appcast failed validation.")
        print(
            "Signed production appcast generated and validated: "
            f"{appcast_path} ({validation.matched_enclosure_count} matching enclosure(s))"
        )
    else:
        print(f"Production appcast generated: {appcast_path}")
    return appcast_path


def get_github_releases(repo_owner: str, repo_name: str, token: str | None = None) -> list[dict[str, object]]:
    """Fetch GitHub releases using GitHub API for diagnostic appcasts."""
    url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/releases"
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = Request(url, headers=headers)
    try:
        with urlopen(request, timeout=30) as response:
            loaded = json.loads(response.read().decode("utf-8"))
            return loaded if isinstance(loaded, list) else []
    except (OSError, URLError, json.JSONDecodeError) as exc:
        print(f"Error fetching GitHub releases: {exc}", file=sys.stderr)
        return []


def create_diagnostic_appcast_from_github(
    repo_owner: str,
    repo_name: str,
    output_file: Path,
    token: str | None = None,
) -> Path:
    """Create unsigned diagnostic Sparkle appcast XML from GitHub releases."""
    releases = get_github_releases(repo_owner, repo_name, token)
    rss, channel = _new_rss_channel(f"https://github.com/{repo_owner}/{repo_name}")

    for release in releases:
        if release.get("draft") or release.get("prerelease"):
            continue
        tag_name = str(release.get("tag_name", ""))
        version = normalize_release_version(tag_name)
        assets = release.get("assets")
        if not isinstance(assets, list):
            continue
        dmg_asset = next(
            (asset for asset in assets if isinstance(asset, dict) and str(asset.get("name", "")).endswith(".dmg")),
            None,
        )
        if not dmg_asset:
            continue
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = f"MotionSmith {version}"
        ET.SubElement(item, "sparkle:version").text = version
        ET.SubElement(item, "sparkle:shortVersionString").text = version
        ET.SubElement(item, "description").text = str(release.get("body") or f"Update to {version}")
        published_at = str(release.get("published_at", "1970-01-01T00:00:00Z"))
        pub_date = datetime.fromisoformat(published_at.replace("Z", "+00:00"))
        ET.SubElement(item, "pubDate").text = pub_date.strftime("%a, %d %b %Y %H:%M:%S +0000")
        enclosure = ET.SubElement(item, "enclosure")
        enclosure.set("url", str(dmg_asset.get("browser_download_url", "")))
        enclosure.set("length", str(dmg_asset.get("size", "0")))
        enclosure.set("type", "application/octet-stream")
        ET.SubElement(item, "sparkle:minimumSystemVersion").text = "10.15"
        if release.get("html_url"):
            ET.SubElement(item, "sparkle:releaseNotesLink").text = str(release["html_url"])

    _write_xml(rss, output_file)
    print(f"Diagnostic appcast created: {output_file}")
    return output_file


def create_diagnostic_appcast(releases_dir: Path, base_url: str, output_file: str = "appcast.xml") -> Path:
    """Create unsigned diagnostic Sparkle appcast XML from local files."""
    rss, channel = _new_rss_channel(base_url)
    dmg_files = sorted(releases_dir.glob("*.dmg"), key=lambda path: path.stat().st_mtime, reverse=True)

    for dmg_file in dmg_files:
        filename = dmg_file.stem
        version = filename.split("-v", 1)[1] if "-v" in filename else str(int(dmg_file.stat().st_mtime))
        size, sha256 = get_file_info(dmg_file)
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = f"MotionSmith {version}"
        ET.SubElement(item, "sparkle:version").text = version
        ET.SubElement(item, "sparkle:shortVersionString").text = version
        ET.SubElement(item, "description").text = f"Update to version {version}"
        ET.SubElement(item, "pubDate").text = datetime.fromtimestamp(
            dmg_file.stat().st_mtime
        ).strftime("%a, %d %b %Y %H:%M:%S +0000")
        enclosure = ET.SubElement(item, "enclosure")
        enclosure.set("url", f"{base_url.rstrip('/')}/{dmg_file.name}")
        enclosure.set("length", str(size))
        enclosure.set("type", "application/octet-stream")
        enclosure.set("sparkle:sha256Sum", sha256)
        ET.SubElement(item, "sparkle:minimumSystemVersion").text = "10.15"

    output_path = releases_dir / output_file
    _write_xml(rss, output_path)
    print(f"Diagnostic appcast created: {output_path}")
    return output_path


def _new_rss_channel(link: str) -> tuple[ET.Element, ET.Element]:
    rss = ET.Element("rss", version="2.0")
    rss.set("xmlns:sparkle", "http://www.andymatuschak.org/xml-namespaces/sparkle")
    rss.set("xmlns:dc", "http://purl.org/dc/elements/1.1/")
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = "MotionSmith Updates"
    ET.SubElement(channel, "link").text = link
    ET.SubElement(channel, "description").text = "Updates for MotionSmith application"
    ET.SubElement(channel, "language").text = "en"
    return rss, channel


def _write_xml(root: ET.Element, output_path: Path) -> None:
    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ", level=0)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("wb") as handle:
        handle.write(b'<?xml version="1.0" encoding="utf-8"?>\n')
        tree.write(handle, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command")

    production = subparsers.add_parser(
        "production",
        help="Generate a production Sparkle appcast using official Sparkle generate_appcast.",
    )
    production.add_argument("--artifact", type=Path, action="append", required=True)
    production.add_argument("--output-dir", type=Path, required=True)
    production.add_argument("--download-url-prefix", default=UPDATE_SITE_BASE_URL)
    production.add_argument("--link", default=UPDATE_SITE_BASE_URL)
    production.add_argument("--appcast-name", default=Path(DEFAULT_APPCAST_URL).name)
    production.add_argument("--expected-artifact")
    production.add_argument("--expected-version", required=True)
    production.add_argument("--release-notes", type=Path)
    production.add_argument("--embed-release-notes", action="store_true")
    production.add_argument("--maximum-versions", type=int, default=3)
    production.add_argument(
        "--private-key-env",
        help=(
            "Environment variable containing the private EdDSA key. When omitted, "
            "Sparkle reads the key from the Keychain."
        ),
    )
    production.add_argument("--keychain-account")
    production.add_argument("--sparkle-generate-appcast")
    production.add_argument("--sparkle-bin-dir")
    production.add_argument("--sparkle-distribution-dir")
    production.add_argument("--allow-path-tool", action="store_true")
    production.add_argument("--no-clean", dest="clean", action="store_false")
    production.add_argument("--no-validate", dest="validate", action="store_false")
    production.set_defaults(func=generate_production_appcast, clean=True, validate=True)

    github = subparsers.add_parser(
        "diagnostic-github",
        help="Generate an unsigned diagnostic appcast from GitHub release metadata.",
    )
    github.add_argument("repo", help="owner/repo")
    github.add_argument("output", type=Path)
    github.set_defaults(func=_diagnostic_github_command)

    local = subparsers.add_parser(
        "diagnostic-local",
        help="Generate an unsigned diagnostic appcast from local DMG files.",
    )
    local.add_argument("releases_dir", type=Path)
    local.add_argument("base_url")
    local.add_argument("--output-file", default="appcast.xml")
    local.set_defaults(func=_diagnostic_local_command)
    return parser


def _diagnostic_github_command(args: argparse.Namespace) -> Path:
    owner, separator, repo = args.repo.partition("/")
    if not separator:
        raise AppcastGenerationError("Repository must be in owner/repo form.")
    return create_diagnostic_appcast_from_github(
        owner,
        repo,
        args.output,
        token=os.environ.get("GITHUB_TOKEN"),
    )


def _diagnostic_local_command(args: argparse.Namespace) -> Path:
    if not args.releases_dir.exists():
        raise AppcastGenerationError(f"Releases directory does not exist: {args.releases_dir}")
    return create_diagnostic_appcast(args.releases_dir, args.base_url, args.output_file)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not hasattr(args, "func"):
        parser.print_help()
        return 1
    try:
        args.func(args)
    except AppcastGenerationError as exc:
        print(f"::error::{exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
